/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhiteLabelPartnershipRouteImport } from './routes/white-label-partnership'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PressReleaseRouteImport } from './routes/press-release'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MyTestimonialsRouteImport } from './routes/my-testimonials'
import { Route as MyCertificationsRouteImport } from './routes/my-certifications'
import { Route as MyAwardsRouteImport } from './routes/my-awards'
import { Route as MediaKitRouteImport } from './routes/media-kit'
import { Route as LogRouteImport } from './routes/log'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as ContactMeRouteImport } from './routes/contact-me'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutMeRouteImport } from './routes/about-me'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsExpertiseIndexRouteImport } from './routes/skills-expertise.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as MyLifestyleIndexRouteImport } from './routes/my-lifestyle.index'
import { Route as SkillsExpertiseTechnicalSkillsRouteImport } from './routes/skills-expertise.technical-skills'
import { Route as SkillsExpertiseSeoMarketingRouteImport } from './routes/skills-expertise.seo-marketing'
import { Route as SkillsExpertiseCreativeSkillsRouteImport } from './routes/skills-expertise.creative-skills'
import { Route as SkillsExpertiseAiResearchAndInnovationRouteImport } from './routes/skills-expertise.ai-research-and-innovation'
import { Route as ServicesWebRouteImport } from './routes/services.web'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as PortfolioWebsitesRouteImport } from './routes/portfolio.websites'
import { Route as PortfolioGamingLifeRouteImport } from './routes/portfolio.gaming-life'
import { Route as PortfolioCreativeProjectsRouteImport } from './routes/portfolio.creative-projects'
import { Route as PortfolioBrandsBusinessesRouteImport } from './routes/portfolio.brands-businesses'
import { Route as MyLifestyleHobbiesRouteImport } from './routes/my-lifestyle.hobbies'
import { Route as MyLifestyleGamingLifeRouteImport } from './routes/my-lifestyle.gaming-life'
import { Route as MyLifestyleFitnessHealthRouteImport } from './routes/my-lifestyle.fitness-health'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal.privacy-policy'
import { Route as LegalOurTermsRouteImport } from './routes/legal.our-terms'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AboutMeVisionValuesRouteImport } from './routes/about-me.vision-values'
import { Route as AboutMeSocialMediaRouteImport } from './routes/about-me.social-media'
import { Route as AboutMePersonalLifeRouteImport } from './routes/about-me.personal-life'
import { Route as AboutMeMyJourneyRouteImport } from './routes/about-me.my-journey'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const WhiteLabelPartnershipRoute = WhiteLabelPartnershipRouteImport.update({
  id: '/white-label-partnership',
  path: '/white-label-partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PressReleaseRoute = PressReleaseRouteImport.update({
  id: '/press-release',
  path: '/press-release',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTestimonialsRoute = MyTestimonialsRouteImport.update({
  id: '/my-testimonials',
  path: '/my-testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCertificationsRoute = MyCertificationsRouteImport.update({
  id: '/my-certifications',
  path: '/my-certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAwardsRoute = MyAwardsRouteImport.update({
  id: '/my-awards',
  path: '/my-awards',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaKitRoute = MediaKitRouteImport.update({
  id: '/media-kit',
  path: '/media-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactMeRoute = ContactMeRouteImport.update({
  id: '/contact-me',
  path: '/contact-me',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMeRoute = AboutMeRouteImport.update({
  id: '/about-me',
  path: '/about-me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsExpertiseIndexRoute = SkillsExpertiseIndexRouteImport.update({
  id: '/skills-expertise/',
  path: '/skills-expertise/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLifestyleIndexRoute = MyLifestyleIndexRouteImport.update({
  id: '/my-lifestyle/',
  path: '/my-lifestyle/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsExpertiseTechnicalSkillsRoute =
  SkillsExpertiseTechnicalSkillsRouteImport.update({
    id: '/skills-expertise/technical-skills',
    path: '/skills-expertise/technical-skills',
    getParentRoute: () => rootRouteImport,
  } as any)
const SkillsExpertiseSeoMarketingRoute =
  SkillsExpertiseSeoMarketingRouteImport.update({
    id: '/skills-expertise/seo-marketing',
    path: '/skills-expertise/seo-marketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const SkillsExpertiseCreativeSkillsRoute =
  SkillsExpertiseCreativeSkillsRouteImport.update({
    id: '/skills-expertise/creative-skills',
    path: '/skills-expertise/creative-skills',
    getParentRoute: () => rootRouteImport,
  } as any)
const SkillsExpertiseAiResearchAndInnovationRoute =
  SkillsExpertiseAiResearchAndInnovationRouteImport.update({
    id: '/skills-expertise/ai-research-and-innovation',
    path: '/skills-expertise/ai-research-and-innovation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesWebRoute = ServicesWebRouteImport.update({
  id: '/services/web',
  path: '/services/web',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioWebsitesRoute = PortfolioWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioGamingLifeRoute = PortfolioGamingLifeRouteImport.update({
  id: '/gaming-life',
  path: '/gaming-life',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioCreativeProjectsRoute =
  PortfolioCreativeProjectsRouteImport.update({
    id: '/creative-projects',
    path: '/creative-projects',
    getParentRoute: () => PortfolioRoute,
  } as any)
const PortfolioBrandsBusinessesRoute =
  PortfolioBrandsBusinessesRouteImport.update({
    id: '/brands-businesses',
    path: '/brands-businesses',
    getParentRoute: () => PortfolioRoute,
  } as any)
const MyLifestyleHobbiesRoute = MyLifestyleHobbiesRouteImport.update({
  id: '/my-lifestyle/hobbies',
  path: '/my-lifestyle/hobbies',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLifestyleGamingLifeRoute = MyLifestyleGamingLifeRouteImport.update({
  id: '/my-lifestyle/gaming-life',
  path: '/my-lifestyle/gaming-life',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLifestyleFitnessHealthRoute =
  MyLifestyleFitnessHealthRouteImport.update({
    id: '/my-lifestyle/fitness-health',
    path: '/my-lifestyle/fitness-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalOurTermsRoute = LegalOurTermsRouteImport.update({
  id: '/our-terms',
  path: '/our-terms',
  getParentRoute: () => LegalRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AboutMeVisionValuesRoute = AboutMeVisionValuesRouteImport.update({
  id: '/vision-values',
  path: '/vision-values',
  getParentRoute: () => AboutMeRoute,
} as any)
const AboutMeSocialMediaRoute = AboutMeSocialMediaRouteImport.update({
  id: '/social-media',
  path: '/social-media',
  getParentRoute: () => AboutMeRoute,
} as any)
const AboutMePersonalLifeRoute = AboutMePersonalLifeRouteImport.update({
  id: '/personal-life',
  path: '/personal-life',
  getParentRoute: () => AboutMeRoute,
} as any)
const AboutMeMyJourneyRoute = AboutMeMyJourneyRouteImport.update({
  id: '/my-journey',
  path: '/my-journey',
  getParentRoute: () => AboutMeRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRouteWithChildren
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/blog': typeof BlogRouteWithChildren
  '/businesses': typeof BusinessesRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/contact-me': typeof ContactMeRoute
  '/contact-us': typeof ContactUsRoute
  '/courses': typeof CoursesRoute
  '/legal': typeof LegalRouteWithChildren
  '/log': typeof LogRoute
  '/media-kit': typeof MediaKitRoute
  '/my-awards': typeof MyAwardsRoute
  '/my-certifications': typeof MyCertificationsRoute
  '/my-testimonials': typeof MyTestimonialsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/press-release': typeof PressReleaseRoute
  '/shop': typeof ShopRoute
  '/testimonials': typeof TestimonialsRoute
  '/trust': typeof TrustRoute
  '/white-label-partnership': typeof WhiteLabelPartnershipRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/import': typeof AuthenticatedImportRoute
  '/about-me/my-journey': typeof AboutMeMyJourneyRoute
  '/about-me/personal-life': typeof AboutMePersonalLifeRoute
  '/about-me/social-media': typeof AboutMeSocialMediaRoute
  '/about-me/vision-values': typeof AboutMeVisionValuesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/legal/our-terms': typeof LegalOurTermsRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/my-lifestyle/fitness-health': typeof MyLifestyleFitnessHealthRoute
  '/my-lifestyle/gaming-life': typeof MyLifestyleGamingLifeRoute
  '/my-lifestyle/hobbies': typeof MyLifestyleHobbiesRoute
  '/portfolio/brands-businesses': typeof PortfolioBrandsBusinessesRoute
  '/portfolio/creative-projects': typeof PortfolioCreativeProjectsRoute
  '/portfolio/gaming-life': typeof PortfolioGamingLifeRoute
  '/portfolio/websites': typeof PortfolioWebsitesRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/web': typeof ServicesWebRoute
  '/skills-expertise/ai-research-and-innovation': typeof SkillsExpertiseAiResearchAndInnovationRoute
  '/skills-expertise/creative-skills': typeof SkillsExpertiseCreativeSkillsRoute
  '/skills-expertise/seo-marketing': typeof SkillsExpertiseSeoMarketingRoute
  '/skills-expertise/technical-skills': typeof SkillsExpertiseTechnicalSkillsRoute
  '/my-lifestyle/': typeof MyLifestyleIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/skills-expertise/': typeof SkillsExpertiseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRouteWithChildren
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/blog': typeof BlogRouteWithChildren
  '/businesses': typeof BusinessesRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/contact-me': typeof ContactMeRoute
  '/contact-us': typeof ContactUsRoute
  '/courses': typeof CoursesRoute
  '/legal': typeof LegalRouteWithChildren
  '/log': typeof LogRoute
  '/media-kit': typeof MediaKitRoute
  '/my-awards': typeof MyAwardsRoute
  '/my-certifications': typeof MyCertificationsRoute
  '/my-testimonials': typeof MyTestimonialsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/press-release': typeof PressReleaseRoute
  '/shop': typeof ShopRoute
  '/testimonials': typeof TestimonialsRoute
  '/trust': typeof TrustRoute
  '/white-label-partnership': typeof WhiteLabelPartnershipRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/import': typeof AuthenticatedImportRoute
  '/about-me/my-journey': typeof AboutMeMyJourneyRoute
  '/about-me/personal-life': typeof AboutMePersonalLifeRoute
  '/about-me/social-media': typeof AboutMeSocialMediaRoute
  '/about-me/vision-values': typeof AboutMeVisionValuesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/legal/our-terms': typeof LegalOurTermsRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/my-lifestyle/fitness-health': typeof MyLifestyleFitnessHealthRoute
  '/my-lifestyle/gaming-life': typeof MyLifestyleGamingLifeRoute
  '/my-lifestyle/hobbies': typeof MyLifestyleHobbiesRoute
  '/portfolio/brands-businesses': typeof PortfolioBrandsBusinessesRoute
  '/portfolio/creative-projects': typeof PortfolioCreativeProjectsRoute
  '/portfolio/gaming-life': typeof PortfolioGamingLifeRoute
  '/portfolio/websites': typeof PortfolioWebsitesRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/web': typeof ServicesWebRoute
  '/skills-expertise/ai-research-and-innovation': typeof SkillsExpertiseAiResearchAndInnovationRoute
  '/skills-expertise/creative-skills': typeof SkillsExpertiseCreativeSkillsRoute
  '/skills-expertise/seo-marketing': typeof SkillsExpertiseSeoMarketingRoute
  '/skills-expertise/technical-skills': typeof SkillsExpertiseTechnicalSkillsRoute
  '/my-lifestyle': typeof MyLifestyleIndexRoute
  '/services': typeof ServicesIndexRoute
  '/skills-expertise': typeof SkillsExpertiseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about-me': typeof AboutMeRouteWithChildren
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/blog': typeof BlogRouteWithChildren
  '/businesses': typeof BusinessesRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/contact-me': typeof ContactMeRoute
  '/contact-us': typeof ContactUsRoute
  '/courses': typeof CoursesRoute
  '/legal': typeof LegalRouteWithChildren
  '/log': typeof LogRoute
  '/media-kit': typeof MediaKitRoute
  '/my-awards': typeof MyAwardsRoute
  '/my-certifications': typeof MyCertificationsRoute
  '/my-testimonials': typeof MyTestimonialsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/press-release': typeof PressReleaseRoute
  '/shop': typeof ShopRoute
  '/testimonials': typeof TestimonialsRoute
  '/trust': typeof TrustRoute
  '/white-label-partnership': typeof WhiteLabelPartnershipRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/about-me/my-journey': typeof AboutMeMyJourneyRoute
  '/about-me/personal-life': typeof AboutMePersonalLifeRoute
  '/about-me/social-media': typeof AboutMeSocialMediaRoute
  '/about-me/vision-values': typeof AboutMeVisionValuesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/legal/our-terms': typeof LegalOurTermsRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/my-lifestyle/fitness-health': typeof MyLifestyleFitnessHealthRoute
  '/my-lifestyle/gaming-life': typeof MyLifestyleGamingLifeRoute
  '/my-lifestyle/hobbies': typeof MyLifestyleHobbiesRoute
  '/portfolio/brands-businesses': typeof PortfolioBrandsBusinessesRoute
  '/portfolio/creative-projects': typeof PortfolioCreativeProjectsRoute
  '/portfolio/gaming-life': typeof PortfolioGamingLifeRoute
  '/portfolio/websites': typeof PortfolioWebsitesRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/web': typeof ServicesWebRoute
  '/skills-expertise/ai-research-and-innovation': typeof SkillsExpertiseAiResearchAndInnovationRoute
  '/skills-expertise/creative-skills': typeof SkillsExpertiseCreativeSkillsRoute
  '/skills-expertise/seo-marketing': typeof SkillsExpertiseSeoMarketingRoute
  '/skills-expertise/technical-skills': typeof SkillsExpertiseTechnicalSkillsRoute
  '/my-lifestyle/': typeof MyLifestyleIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/skills-expertise/': typeof SkillsExpertiseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-me'
    | '/auth'
    | '/awards'
    | '/blog'
    | '/businesses'
    | '/careers'
    | '/case-studies'
    | '/certifications'
    | '/contact'
    | '/contact-me'
    | '/contact-us'
    | '/courses'
    | '/legal'
    | '/log'
    | '/media-kit'
    | '/my-awards'
    | '/my-certifications'
    | '/my-testimonials'
    | '/portfolio'
    | '/press-release'
    | '/shop'
    | '/testimonials'
    | '/trust'
    | '/white-label-partnership'
    | '/admin'
    | '/import'
    | '/about-me/my-journey'
    | '/about-me/personal-life'
    | '/about-me/social-media'
    | '/about-me/vision-values'
    | '/blog/$slug'
    | '/category/$slug'
    | '/legal/our-terms'
    | '/legal/privacy-policy'
    | '/my-lifestyle/fitness-health'
    | '/my-lifestyle/gaming-life'
    | '/my-lifestyle/hobbies'
    | '/portfolio/brands-businesses'
    | '/portfolio/creative-projects'
    | '/portfolio/gaming-life'
    | '/portfolio/websites'
    | '/services/$slug'
    | '/services/web'
    | '/skills-expertise/ai-research-and-innovation'
    | '/skills-expertise/creative-skills'
    | '/skills-expertise/seo-marketing'
    | '/skills-expertise/technical-skills'
    | '/my-lifestyle/'
    | '/services/'
    | '/skills-expertise/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-me'
    | '/auth'
    | '/awards'
    | '/blog'
    | '/businesses'
    | '/careers'
    | '/case-studies'
    | '/certifications'
    | '/contact'
    | '/contact-me'
    | '/contact-us'
    | '/courses'
    | '/legal'
    | '/log'
    | '/media-kit'
    | '/my-awards'
    | '/my-certifications'
    | '/my-testimonials'
    | '/portfolio'
    | '/press-release'
    | '/shop'
    | '/testimonials'
    | '/trust'
    | '/white-label-partnership'
    | '/admin'
    | '/import'
    | '/about-me/my-journey'
    | '/about-me/personal-life'
    | '/about-me/social-media'
    | '/about-me/vision-values'
    | '/blog/$slug'
    | '/category/$slug'
    | '/legal/our-terms'
    | '/legal/privacy-policy'
    | '/my-lifestyle/fitness-health'
    | '/my-lifestyle/gaming-life'
    | '/my-lifestyle/hobbies'
    | '/portfolio/brands-businesses'
    | '/portfolio/creative-projects'
    | '/portfolio/gaming-life'
    | '/portfolio/websites'
    | '/services/$slug'
    | '/services/web'
    | '/skills-expertise/ai-research-and-innovation'
    | '/skills-expertise/creative-skills'
    | '/skills-expertise/seo-marketing'
    | '/skills-expertise/technical-skills'
    | '/my-lifestyle'
    | '/services'
    | '/skills-expertise'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about-me'
    | '/auth'
    | '/awards'
    | '/blog'
    | '/businesses'
    | '/careers'
    | '/case-studies'
    | '/certifications'
    | '/contact'
    | '/contact-me'
    | '/contact-us'
    | '/courses'
    | '/legal'
    | '/log'
    | '/media-kit'
    | '/my-awards'
    | '/my-certifications'
    | '/my-testimonials'
    | '/portfolio'
    | '/press-release'
    | '/shop'
    | '/testimonials'
    | '/trust'
    | '/white-label-partnership'
    | '/_authenticated/admin'
    | '/_authenticated/import'
    | '/about-me/my-journey'
    | '/about-me/personal-life'
    | '/about-me/social-media'
    | '/about-me/vision-values'
    | '/blog/$slug'
    | '/category/$slug'
    | '/legal/our-terms'
    | '/legal/privacy-policy'
    | '/my-lifestyle/fitness-health'
    | '/my-lifestyle/gaming-life'
    | '/my-lifestyle/hobbies'
    | '/portfolio/brands-businesses'
    | '/portfolio/creative-projects'
    | '/portfolio/gaming-life'
    | '/portfolio/websites'
    | '/services/$slug'
    | '/services/web'
    | '/skills-expertise/ai-research-and-innovation'
    | '/skills-expertise/creative-skills'
    | '/skills-expertise/seo-marketing'
    | '/skills-expertise/technical-skills'
    | '/my-lifestyle/'
    | '/services/'
    | '/skills-expertise/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutMeRoute: typeof AboutMeRouteWithChildren
  AuthRoute: typeof AuthRoute
  AwardsRoute: typeof AwardsRoute
  BlogRoute: typeof BlogRouteWithChildren
  BusinessesRoute: typeof BusinessesRoute
  CareersRoute: typeof CareersRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  CertificationsRoute: typeof CertificationsRoute
  ContactRoute: typeof ContactRoute
  ContactMeRoute: typeof ContactMeRoute
  ContactUsRoute: typeof ContactUsRoute
  CoursesRoute: typeof CoursesRoute
  LegalRoute: typeof LegalRouteWithChildren
  LogRoute: typeof LogRoute
  MediaKitRoute: typeof MediaKitRoute
  MyAwardsRoute: typeof MyAwardsRoute
  MyCertificationsRoute: typeof MyCertificationsRoute
  MyTestimonialsRoute: typeof MyTestimonialsRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PressReleaseRoute: typeof PressReleaseRoute
  ShopRoute: typeof ShopRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TrustRoute: typeof TrustRoute
  WhiteLabelPartnershipRoute: typeof WhiteLabelPartnershipRoute
  CategorySlugRoute: typeof CategorySlugRoute
  MyLifestyleFitnessHealthRoute: typeof MyLifestyleFitnessHealthRoute
  MyLifestyleGamingLifeRoute: typeof MyLifestyleGamingLifeRoute
  MyLifestyleHobbiesRoute: typeof MyLifestyleHobbiesRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesWebRoute: typeof ServicesWebRoute
  SkillsExpertiseAiResearchAndInnovationRoute: typeof SkillsExpertiseAiResearchAndInnovationRoute
  SkillsExpertiseCreativeSkillsRoute: typeof SkillsExpertiseCreativeSkillsRoute
  SkillsExpertiseSeoMarketingRoute: typeof SkillsExpertiseSeoMarketingRoute
  SkillsExpertiseTechnicalSkillsRoute: typeof SkillsExpertiseTechnicalSkillsRoute
  MyLifestyleIndexRoute: typeof MyLifestyleIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  SkillsExpertiseIndexRoute: typeof SkillsExpertiseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/white-label-partnership': {
      id: '/white-label-partnership'
      path: '/white-label-partnership'
      fullPath: '/white-label-partnership'
      preLoaderRoute: typeof WhiteLabelPartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press-release': {
      id: '/press-release'
      path: '/press-release'
      fullPath: '/press-release'
      preLoaderRoute: typeof PressReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-testimonials': {
      id: '/my-testimonials'
      path: '/my-testimonials'
      fullPath: '/my-testimonials'
      preLoaderRoute: typeof MyTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-certifications': {
      id: '/my-certifications'
      path: '/my-certifications'
      fullPath: '/my-certifications'
      preLoaderRoute: typeof MyCertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-awards': {
      id: '/my-awards'
      path: '/my-awards'
      fullPath: '/my-awards'
      preLoaderRoute: typeof MyAwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-kit': {
      id: '/media-kit'
      path: '/media-kit'
      fullPath: '/media-kit'
      preLoaderRoute: typeof MediaKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-me': {
      id: '/contact-me'
      path: '/contact-me'
      fullPath: '/contact-me'
      preLoaderRoute: typeof ContactMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-me': {
      id: '/about-me'
      path: '/about-me'
      fullPath: '/about-me'
      preLoaderRoute: typeof AboutMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills-expertise/': {
      id: '/skills-expertise/'
      path: '/skills-expertise'
      fullPath: '/skills-expertise/'
      preLoaderRoute: typeof SkillsExpertiseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-lifestyle/': {
      id: '/my-lifestyle/'
      path: '/my-lifestyle'
      fullPath: '/my-lifestyle/'
      preLoaderRoute: typeof MyLifestyleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills-expertise/technical-skills': {
      id: '/skills-expertise/technical-skills'
      path: '/skills-expertise/technical-skills'
      fullPath: '/skills-expertise/technical-skills'
      preLoaderRoute: typeof SkillsExpertiseTechnicalSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills-expertise/seo-marketing': {
      id: '/skills-expertise/seo-marketing'
      path: '/skills-expertise/seo-marketing'
      fullPath: '/skills-expertise/seo-marketing'
      preLoaderRoute: typeof SkillsExpertiseSeoMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills-expertise/creative-skills': {
      id: '/skills-expertise/creative-skills'
      path: '/skills-expertise/creative-skills'
      fullPath: '/skills-expertise/creative-skills'
      preLoaderRoute: typeof SkillsExpertiseCreativeSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills-expertise/ai-research-and-innovation': {
      id: '/skills-expertise/ai-research-and-innovation'
      path: '/skills-expertise/ai-research-and-innovation'
      fullPath: '/skills-expertise/ai-research-and-innovation'
      preLoaderRoute: typeof SkillsExpertiseAiResearchAndInnovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web': {
      id: '/services/web'
      path: '/services/web'
      fullPath: '/services/web'
      preLoaderRoute: typeof ServicesWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/websites': {
      id: '/portfolio/websites'
      path: '/websites'
      fullPath: '/portfolio/websites'
      preLoaderRoute: typeof PortfolioWebsitesRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/gaming-life': {
      id: '/portfolio/gaming-life'
      path: '/gaming-life'
      fullPath: '/portfolio/gaming-life'
      preLoaderRoute: typeof PortfolioGamingLifeRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/creative-projects': {
      id: '/portfolio/creative-projects'
      path: '/creative-projects'
      fullPath: '/portfolio/creative-projects'
      preLoaderRoute: typeof PortfolioCreativeProjectsRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/brands-businesses': {
      id: '/portfolio/brands-businesses'
      path: '/brands-businesses'
      fullPath: '/portfolio/brands-businesses'
      preLoaderRoute: typeof PortfolioBrandsBusinessesRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/my-lifestyle/hobbies': {
      id: '/my-lifestyle/hobbies'
      path: '/my-lifestyle/hobbies'
      fullPath: '/my-lifestyle/hobbies'
      preLoaderRoute: typeof MyLifestyleHobbiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-lifestyle/gaming-life': {
      id: '/my-lifestyle/gaming-life'
      path: '/my-lifestyle/gaming-life'
      fullPath: '/my-lifestyle/gaming-life'
      preLoaderRoute: typeof MyLifestyleGamingLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-lifestyle/fitness-health': {
      id: '/my-lifestyle/fitness-health'
      path: '/my-lifestyle/fitness-health'
      fullPath: '/my-lifestyle/fitness-health'
      preLoaderRoute: typeof MyLifestyleFitnessHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/our-terms': {
      id: '/legal/our-terms'
      path: '/our-terms'
      fullPath: '/legal/our-terms'
      preLoaderRoute: typeof LegalOurTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/about-me/vision-values': {
      id: '/about-me/vision-values'
      path: '/vision-values'
      fullPath: '/about-me/vision-values'
      preLoaderRoute: typeof AboutMeVisionValuesRouteImport
      parentRoute: typeof AboutMeRoute
    }
    '/about-me/social-media': {
      id: '/about-me/social-media'
      path: '/social-media'
      fullPath: '/about-me/social-media'
      preLoaderRoute: typeof AboutMeSocialMediaRouteImport
      parentRoute: typeof AboutMeRoute
    }
    '/about-me/personal-life': {
      id: '/about-me/personal-life'
      path: '/personal-life'
      fullPath: '/about-me/personal-life'
      preLoaderRoute: typeof AboutMePersonalLifeRouteImport
      parentRoute: typeof AboutMeRoute
    }
    '/about-me/my-journey': {
      id: '/about-me/my-journey'
      path: '/my-journey'
      fullPath: '/about-me/my-journey'
      preLoaderRoute: typeof AboutMeMyJourneyRouteImport
      parentRoute: typeof AboutMeRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AboutMeRouteChildren {
  AboutMeMyJourneyRoute: typeof AboutMeMyJourneyRoute
  AboutMePersonalLifeRoute: typeof AboutMePersonalLifeRoute
  AboutMeSocialMediaRoute: typeof AboutMeSocialMediaRoute
  AboutMeVisionValuesRoute: typeof AboutMeVisionValuesRoute
}

const AboutMeRouteChildren: AboutMeRouteChildren = {
  AboutMeMyJourneyRoute: AboutMeMyJourneyRoute,
  AboutMePersonalLifeRoute: AboutMePersonalLifeRoute,
  AboutMeSocialMediaRoute: AboutMeSocialMediaRoute,
  AboutMeVisionValuesRoute: AboutMeVisionValuesRoute,
}

const AboutMeRouteWithChildren =
  AboutMeRoute._addFileChildren(AboutMeRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface LegalRouteChildren {
  LegalOurTermsRoute: typeof LegalOurTermsRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalOurTermsRoute: LegalOurTermsRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface PortfolioRouteChildren {
  PortfolioBrandsBusinessesRoute: typeof PortfolioBrandsBusinessesRoute
  PortfolioCreativeProjectsRoute: typeof PortfolioCreativeProjectsRoute
  PortfolioGamingLifeRoute: typeof PortfolioGamingLifeRoute
  PortfolioWebsitesRoute: typeof PortfolioWebsitesRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioBrandsBusinessesRoute: PortfolioBrandsBusinessesRoute,
  PortfolioCreativeProjectsRoute: PortfolioCreativeProjectsRoute,
  PortfolioGamingLifeRoute: PortfolioGamingLifeRoute,
  PortfolioWebsitesRoute: PortfolioWebsitesRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutMeRoute: AboutMeRouteWithChildren,
  AuthRoute: AuthRoute,
  AwardsRoute: AwardsRoute,
  BlogRoute: BlogRouteWithChildren,
  BusinessesRoute: BusinessesRoute,
  CareersRoute: CareersRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  CertificationsRoute: CertificationsRoute,
  ContactRoute: ContactRoute,
  ContactMeRoute: ContactMeRoute,
  ContactUsRoute: ContactUsRoute,
  CoursesRoute: CoursesRoute,
  LegalRoute: LegalRouteWithChildren,
  LogRoute: LogRoute,
  MediaKitRoute: MediaKitRoute,
  MyAwardsRoute: MyAwardsRoute,
  MyCertificationsRoute: MyCertificationsRoute,
  MyTestimonialsRoute: MyTestimonialsRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PressReleaseRoute: PressReleaseRoute,
  ShopRoute: ShopRoute,
  TestimonialsRoute: TestimonialsRoute,
  TrustRoute: TrustRoute,
  WhiteLabelPartnershipRoute: WhiteLabelPartnershipRoute,
  CategorySlugRoute: CategorySlugRoute,
  MyLifestyleFitnessHealthRoute: MyLifestyleFitnessHealthRoute,
  MyLifestyleGamingLifeRoute: MyLifestyleGamingLifeRoute,
  MyLifestyleHobbiesRoute: MyLifestyleHobbiesRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesWebRoute: ServicesWebRoute,
  SkillsExpertiseAiResearchAndInnovationRoute:
    SkillsExpertiseAiResearchAndInnovationRoute,
  SkillsExpertiseCreativeSkillsRoute: SkillsExpertiseCreativeSkillsRoute,
  SkillsExpertiseSeoMarketingRoute: SkillsExpertiseSeoMarketingRoute,
  SkillsExpertiseTechnicalSkillsRoute: SkillsExpertiseTechnicalSkillsRoute,
  MyLifestyleIndexRoute: MyLifestyleIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  SkillsExpertiseIndexRoute: SkillsExpertiseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
